#most-shelly-client/docker-compose.yml
version: '3.8'

networks:
  most_net:
    external: true

  wg_net:
    ipam:
      config:
      - subnet: 192.168.125.0/24

services:
  wireguard:
    image: procustodibus/wireguard
    hostname: wireguard
    cap_add:
    - NET_ADMIN
    networks:
      wg_net:
        ipv4_address: 192.168.125.125
    ports:
    - 50002:50002/udp
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - "${BASE_PATH}/wireguard:/etc/wireguard"

  mqtt:
    image: eclipse-mosquitto:2.0
    hostname: mqtt
    restart: always
    networks:
      wg_net:
          ipv4_address: 192.168.125.126
      most_net: {}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${BASE_PATH}/mosquitto/config:/mosquitto/config"
      - "${BASE_PATH}/mosquitto/data:/mosquitto/data"
      - "${BASE_PATH}/mosquitto/log:/mosquitto/log"

  whoami:
    image: jwilder/whoami
    networks:
      wg_net:
        ipv4_address: 192.168.125.3
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro

