#most-shelly-client/docker-compose.yml
version: '3.8'

networks:
  most_net:
    external: true

  wg_net:
    ipam:
      config:
      - subnet: 192.168.125.0/24

services:
  wireguard:
    image: procustodibus/wireguard
    hostname: wireguard
    cap_add:
    - NET_ADMIN
    networks:
      wg_net:
        ipv4_address: 192.168.125.125
    ports:
    - 50002:50002/udp
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /opt/most-shelly/wireguard:/etc/wireguard

  mqtt:
    image: eclipse-mosquitto:2.0
    hostname: mqtt
    restart: always
    networks:
      wg_net:
          ipv4_address: 192.168.125.125
      most_net: {}
    #ports:
    #  - "1883:1883"    # MQTT protocol
    #  - "9001:9001"    # WebSocket (optional)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/mostshelly/mosquitto/config:/mosquitto/config
      - /opt/mostshelly/mosquitto/data:/mosquitto/data
      - /opt/mostshelly/mosquitto/log:/mosquitto/log

  whoami-srv:
    image: jwilder/whoami
    networks:
      wg_net:
        ipv4_address: 192.168.125.3
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro

